###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:5.7'
        container_name: appmax-mysql
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db_appmax
            - MYSQL_USER=secret
            - MYSQL_PASSWORD=secret
        ports:
            - '47001:3306'
            
    adminer:
      image: adminer
      container_name: appmax-adminer
      restart: always
      ports:
        - 8080:8080

    webserver:
        image: 'nginx:alpine'
        container_name: appmax-webserver
        working_dir: /application
        volumes:
            - './api:/application'
            - './devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '47000:80'

    php-fpm:
        build: devops/php-fpm
        container_name: appmax-php-fpm
        working_dir: /application
        volumes:
            - './api:/application'
            - './devops/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
